#+TITLE: .emacs.d - Emacs configuration
#+AUTHOR: Nahuel Jesús Sacchetti

* About me

#+BEGIN_QUOTE
I am an enthusiastic Software Engineer who loves to work in a team,
sharing knowledge and experience among peers.
#+END_QUOTE

I started programming when I was 12 years old. I've been working on a
few open source projects as well as doing freelance. At the age of 23, I
started a professional career in Web Frontend, though I still prefer
more logical stuff instead of User Interface.

* Features

- "Stock Emacs".
- Descritive [[file+emacs:configuration.org][configuration]].
- Always up-to-date.
- Fixes the =C-a= to go to indentation if you press twice.
- A low-contrast theme.
- Not disruptive when programming, you do all the work.
- Better defaults are better.
- Support Terminal and Window System, as well as multiple OS.
- Designed to work nicely with =emacs --daemon=.
- Simple and easy to understand mode-line.

* Download This Configuration

My Emacs configuration has some personal touch even though lately I use
mostly a "stock Emacs". I use Terminal Emacs, so most of the colors are
adapted to how my terminals render Emacs.

** Download Emacs in Mac

#+BEGIN_SRC bash
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus --without-spacemacs-icon
#+END_SRC

** Download Emacs in Ubuntu (old version)

#+BEGIN_SRC bash
$ [sudo] add-apt-repository ppa:kelleyk/emacs
$ [sudo] apt-get update
$ [sudo] apt-get install emacs25
#+END_SRC

** Download Emacs in ArchLinux (the best distro ever)

#+BEGIN_SRC bash
[sudo] pacman -S emacs
#+END_SRC

* Contributions

If you see something that can be done in a better way or some
configuration that you consider it's missed go ahead and submit a PR.
