#+TITLE: .emacs.d - Emacs configuration
#+AUTHOR: Nahuel Jesús Sacchetti

* About me
I'm a enthusiastic developer. I love Emacs even though I started to use it recently. I'm currently in love with Elisp as
well so that's a big point towards using Emacs for almost everything.

* Download this configuration
Almost everything here has my personal touch. You are always welcome to download it and also if you see fit you can
submit a pull request. I'm quite special with my configurations but any kind of suggestions are accepted!

You can download this configuration as you please. First you will have to install Emacs. I personally use =emacs-plus=
on my Mac, go ahead and try that out: [[https://github.com/d12frosted/homebrew-emacs-plus][Download emacs-plus]].
#+BEGIN_SRC
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus --without-spacemacs-icon
#+END_SRC

On my Linux (Ubuntu) I use =kelleyk= repository to install Emacs 25.x.
#+BEGIN_SRC
sudo add-apt-repository ppa:kelleyk/emacs
sudo apt-get update
sudo apt-get install emacs25
#+END_SRC

* Using Flycheck as linter
I use =flycheck= package for linting. You should be fine without installing anything but if you want to use its benefits
you will need to install some binaries.

Flycheck is currently active for:
- JavaScript

For JavaScript you should install =eslint=
#+BEGIN_SRC
npm install -g eslint
#+END_SRC

* Contributions
If you see something that can be done in a better way or some configuration that you consider it's missed go ahead and
create a pull request!
