;;; very-basic-theme.el --- A very basic theme

;; Copyright (C) 2019-2020 Nahuel Jesús Sacchetti

;; Author: Nahuel Jesús Sacchetti <me@nsacchetti.com>
;; URL: http://github.com/elnawe/nemacs
;; Package-Version: 20191208
;; Version: 1.0

;; This program is free software; you can redistribute it and/or modify it under
;; the terms of the GNU General Public License as published by the Free Software
;; Foundation, either version 3 of the License, or (at your option) any later
;; version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; A very basic and simple theme.

;;; Code:

(deftheme very-basic "The Very Basic color theme")

(defgroup very-basic-theme nil
  "Very Basic theme."
  :group 'faces
  :prefix "very-basic-theme-"
  :link '(url-link :tag "GitHub" "https://github.com/elnawe/nemacs")
  :tag "Very Basic theme")

(setq vb-colors-alist
  '(("vb-foreground"  . "black")
    ("vb-background"  . "grey94")
    ("vb-subtle"      . "gray50")
    ("vb-very-subtle" . "gray90")
    ("vb-green"       . "SeaGreen")
    ("vb-red"         . "OrangeRed")))
;;"Very Basic colors")

(defmacro with-vb-color-variables (&rest body)
  "Binds all the colors from `vb-colors-alist' around
`body'. Use this macro to wrap the `custom-set-faces' in order to
access the `very-basic' theme color variables."
  (declare (indent 0))
  `(let (,@(mapcar (lambda (cons)
                     (list (intern (car cons)) (cdr cons)))
                   vb-colors-alist))
     ,@body))

(defface org-bullets '()
  "Custom face to be used in `org-bullets-mode'. Use this face in
`org-bullets-face-name' to activate. "
  :group 'org-bullets-mode)

(with-vb-color-variables
  (custom-theme-set-faces
   'very-basic
   `(beacon-fallback-background ((t (:background ,vb-background :foreground unspecified))))
   `(bold ((t (:background unspecified :bold t :foreground unspecified))))
   `(bold-italic ((t (:background unspecified :bold t :foreground unspecified :italic t))))
   `(bookmark-menu-bookmark ((t (:background unspecified :foreground ,vb-foreground))))
   `(bookmark-menu-heading ((t (:background unspecified :foreground ,vb-foreground))))
   `(border ((t (:background unspecified :foreground ,vb-foreground))))
   `(buffer-menu-buffer ((t (:background unspecified :foreground ,vb-foreground))))
   `(button ((t (:background unspecified :bold t :foreground ,vb-foreground))))
   `(calc-nonselected-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(calc-selected-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(calendar-month-header ((t (:background unspecified :foreground ,vb-foreground))))
   `(calendar-today ((t (:background ,vb-foreground :foreground ,vb-background))))
   `(calendar-weekday-header ((t (:background unspecified :foreground ,vb-foreground))))
   `(calendar-weekend-header ((t (:background unspecified :foreground ,vb-foreground))))
   `(comint-highlight-input ((t (:background unspecified :foreground ,vb-foreground))))
   `(comint-highlight-prompt ((t (:background unspecified :foreground ,vb-foreground))))
   `(company-echo ((t (:background unspecified :foreground ,vb-foreground))))
   `(company-echo-common ((t (:background unspecified :foreground ,vb-foreground))))
   `(company-preview ((t (:background unspecified :foreground ,vb-foreground))))
   `(company-preview-common ((t (:background ,vb-very-subtle :foreground ,vb-subtle))))
   `(company-preview-search ((t (:background unspecified :foreground ,vb-foreground))))
   `(company-scrollbar-bg ((t (:background ,vb-foreground :foreground ,vb-foreground))))
   `(company-scrollbar-fg ((t (:background ,vb-subtle :foreground ,vb-foreground))))
   `(company-template-field ((t (:background unspecified :foreground ,vb-foreground))))
   `(company-tooltip ((t (:background ,vb-very-subtle :foreground ,vb-foreground))))
   `(company-tooltip-annotation ((t (:background unspecified :foreground ,vb-foreground))))
   `(company-tooltip-annotation-selection ((t (:background unspecified :foreground unspecified :underline t))))
   `(company-tooltip-common ((t (:background unspecified :foreground ,vb-foreground))))
   `(company-tooltip-common-selection ((t (:background unspecified :foreground unspecified :underline t))))
   `(company-tooltip-mouse ((t (:background unspecified :foreground ,vb-foreground))))
   `(company-tooltip-search ((t (:background unspecified :foreground ,vb-foreground))))
   `(company-tooltip-search-selection ((t (:background unspecified :foreground unspecified :underline t))))
   `(company-tooltip-selection ((t (:background ,vb-foreground :foreground ,vb-background))))
   `(compilation-column-number ((t (:background unspecified :foreground ,vb-foreground))))
   `(compilation-error ((t (:background unspecified :foreground ,vb-foreground))))
   `(compilation-info ((t (:background unspecified :foreground ,vb-foreground))))
   `(compilation-line-number ((t (:background unspecified :foreground ,vb-foreground))))
   `(compilation-mode-line-exit ((t (:background unspecified :foreground ,vb-foreground))))
   `(compilation-mode-line-fail ((t (:background unspecified :foreground ,vb-foreground))))
   `(compilation-mode-line-run ((t (:background unspecified :foreground ,vb-foreground))))
   `(compilation-warning ((t (:background unspecified :foreground ,vb-foreground))))
   `(completions-annotations ((t (:background unspecified :foreground ,vb-foreground))))
   `(completions-common-part ((t (:background unspecified :foreground ,vb-foreground))))
   `(completions-first-difference ((t (:background unspecified :foreground ,vb-foreground))))
   `(cursor ((t (:background ,vb-subtle :foreground unspecified))))
   `(custom-button ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-button-mouse ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-button-pressed ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-button-pressed-unraised ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-button-unraised ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-changed ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-comment ((t (:background unspecified :foreground ,vb-subtle))))
   `(custom-comment-tag ((t (:background unspecified :foreground ,vb-subtle))))
   `(custom-documentation ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-face-tag ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-group-subtitle ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-group-tag ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-group-tag-1 ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-invalid ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-link ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-modified ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-rogue ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-saved ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-set ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-state ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-themed ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-variable-button ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-variable-tag ((t (:background unspecified :foreground ,vb-foreground))))
   `(custom-visibility ((t (:background unspecified :foreground ,vb-foreground))))
   `(dashboard-banner-logo-title ((t (:background unspecified :foreground ,vb-foreground))))
   `(dashboard-footer ((t (:background unspecified :foreground ,vb-foreground))))
   `(dashboard-heading ((t (:background unspecified :foreground ,vb-foreground))))
   `(dashboard-navigator ((t (:background unspecified :foreground ,vb-foreground))))
   `(dashboard-text-banner ((t (:background unspecified :foreground ,vb-foreground))))
   `(default ((t (:background ,vb-background :foreground ,vb-foreground))))
   `(diary ((t (:background unspecified :foreground ,vb-foreground))))
   `(diary-anniversary ((t (:background unspecified :foreground ,vb-foreground))))
   `(diary-button ((t (:background unspecified :foreground ,vb-foreground))))
   `(diary-time ((t (:background unspecified :foreground ,vb-foreground))))
   `(dired-directory ((t (:background unspecified :foreground ,vb-foreground))))
   `(dired-flagged ((t (:background unspecified :foreground ,vb-foreground))))
   `(dired-header ((t (:background unspecified :foreground ,vb-foreground))))
   `(dired-ignored ((t (:background unspecified :foreground ,vb-foreground))))
   `(dired-mark ((t (:background unspecified :foreground ,vb-foreground))))
   `(dired-marked ((t (:background unspecified :foreground ,vb-foreground))))
   `(dired-perm-write ((t (:background unspecified :foreground ,vb-foreground))))
   `(dired-symlink ((t (:background unspecified :foreground ,vb-foreground))))
   `(dired-warning ((t (:background unspecified :foreground ,vb-foreground))))
   `(eldoc-highlight-function-argument ((t (:background unspecified :foreground ,vb-foreground))))
   `(epa-field-body ((t (:background unspecified :foreground ,vb-foreground))))
   `(epa-field-name ((t (:background unspecified :foreground ,vb-foreground))))
   `(epa-mark ((t (:background unspecified :foreground ,vb-foreground))))
   `(epa-string ((t (:background unspecified :foreground ,vb-foreground))))
   `(epa-validity-disabled ((t (:background unspecified :foreground ,vb-foreground))))
   `(epa-validity-high ((t (:background unspecified :foreground ,vb-foreground))))
   `(epa-validity-low ((t (:background unspecified :foreground ,vb-foreground))))
   `(epa-validity-medium ((t (:background unspecified :foreground ,vb-foreground))))
   `(error ((t (:background unspecified :foreground ,vb-foreground))))
   `(escape-glyph ((t (:background unspecified :foreground ,vb-foreground))))
   `(fancy-battery-charging ((t (:background unspecified :foreground ,vb-foreground))))
   `(fancy-battery-critical ((t (:background unspecified :foreground ,vb-foreground))))
   `(fancy-battery-discharging ((t (:background unspecified :foreground ,vb-foreground))))
   `(ffap ((t (:background unspecified :foreground ,vb-foreground))))
   `(file-name-shadow ((t (:background unspecified :foreground ,vb-foreground))))
   `(fixed-pitch ((t (:background unspecified :foreground ,vb-foreground))))
   `(fixed-pitch-serif ((t (:background unspecified :foreground ,vb-foreground))))
   `(flyspell-duplicate ((t (:background unspecified :foreground ,vb-foreground))))
   `(flyspell-incorrect ((t (:background unspecified :foreground ,vb-foreground))))
   `(font-lock-builtin-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(font-lock-comment-delimiter-face ((t (:background unspecified :foreground ,vb-subtle))))
   `(font-lock-comment-face ((t (:background unspecified :foreground ,vb-subtle))))
   `(font-lock-constant-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(font-lock-doc-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(font-lock-function-name-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(font-lock-keyword-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(font-lock-negation-char-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(font-lock-preprocessor-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(font-lock-regexp-grouping-backslash ((t (:background unspecified :foreground ,vb-foreground))))
   `(font-lock-regexp-grouping-construct ((t (:background unspecified :foreground ,vb-foreground))))
   `(font-lock-string-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(font-lock-type-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(font-lock-variable-name-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(font-lock-warning-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(fringe ((t (:background unspecified :foreground ,vb-foreground))))
   `(glyphless-char ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-button ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-cite-1 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-cite-10 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-cite-11 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-cite-2 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-cite-3 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-cite-4 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-cite-5 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-cite-6 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-cite-7 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-cite-8 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-cite-9 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-cite-attribution ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-emphasis-bold ((t (:background unspecified :bold t :foreground unspecified))))
   `(gnus-emphasis-bold-italic ((t (:background unspecified :bold t :foreground unspecified :italic t))))
   `(gnus-emphasis-highlight-words ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-emphasis-italic ((t (:background unspecified :foreground unspecified :italic t))))
   `(gnus-emphasis-strikethru ((t (:background unspecified :foreground unspecified :strike-through t))))
   `(gnus-emphasis-underline ((t (:background unspecified :foreground unspecified :underline t))))
   `(gnus-emphasis-underline-bold ((t (:background unspecified :bold t :foreground unspecified :underline t))))
   `(gnus-emphasis-underline-bold-italic ((t (:background unspecified :bold t :foreground unspecified :italic t))))
   `(gnus-emphasis-underline-italic ((t (:background unspecified :foreground unspecified :italic t :underline t))))
   `(gnus-group-mail-1 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-mail-1-empty ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-mail-2 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-mail-2-empty ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-mail-3 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-mail-3-empty ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-mail-low ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-mail-low-empty ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-news-1 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-news-1-empty ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-news-2 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-news-2-empty ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-news-3 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-news-3-empty ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-news-4 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-news-4-empty ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-news-5 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-news-5-empty ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-news-6 ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-news-6-empty ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-news-low ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-group-news-low-empty ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-header-content ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-header-from ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-header-name ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-header-newsgroups ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-header-subject ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-server-agent ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-server-closed ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-server-cloud ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-server-cloud-host ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-server-denied ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-server-offline ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-server-opened ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-signature ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-splash ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-summary-cancelled ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-summary-high-ancient ((t (:background unspecified :foreground ,vb-subtle))))
   `(gnus-summary-high-read ((t (:background unspecified :foreground ,vb-subtle))))
   `(gnus-summary-high-ticked ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-summary-high-undownloaded ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-summary-high-unread ((t (:background unspecified :bold t :foreground ,vb-foreground))))
   `(gnus-summary-low-ancient ((t (:background unspecified :foreground ,vb-subtle))))
   `(gnus-summary-low-read ((t (:background unspecified :foreground ,vb-subtle))))
   `(gnus-summary-low-ticked ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-summary-low-undownloaded ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-summary-low-unread ((t (:background unspecified :bold t :foreground ,vb-subtle))))
   `(gnus-summary-normal-ancient ((t (:background unspecified :foreground ,vb-subtle))))
   `(gnus-summary-normal-read ((t (:background unspecified :foreground ,vb-subtle))))
   `(gnus-summary-normal-ticked ((t (:background unspecified :bold t :foreground ,vb-subtle))))
   `(gnus-summary-normal-undownloaded ((t (:background unspecified :foreground ,vb-foreground))))
   `(gnus-summary-normal-unread ((t (:background unspecified :bold t :foreground ,vb-foreground))))
   `(gnus-summary-selected ((t (:background unspecified :foreground unspecified :underline t))))
   `(header-line ((t (:background unspecified :foreground ,vb-foreground))))
   `(header-line-highlight ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-M-x-key ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-action ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-bookmark-addressbook ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-bookmark-directory ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-bookmark-file ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-bookmark-file-not-found ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-bookmark-gnus ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-bookmark-info ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-bookmark-man ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-bookmark-w3m ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-buffer-archive ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-buffer-directory ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-buffer-file ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-buffer-modified ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-buffer-not-saved ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-buffer-process ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-buffer-saved-out ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-buffer-size ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-candidate-number ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-candidate-number-suspended ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-delete-async-message ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-eob-line ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-etags-file ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-ff-denied ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-ff-directory ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-ff-dirs ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-ff-dotted-directory ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-ff-dotted-symlink-directory ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-ff-executable ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-ff-file ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-ff-invalid-symlink ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-ff-pipe ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-ff-prefix ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-ff-socket ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-ff-suid ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-ff-symlink ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-ff-truename ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-grep-cmd-line ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-grep-file ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-grep-finish ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-grep-lineno ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-grep-match ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-header ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-header-line-left-margin ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-helper ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-history-deleted ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-history-remote ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-lisp-completion-info ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-lisp-show-completion ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-locate-finish ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-match ((t (:background unspecified :foreground unspecified :underline t))))
   `(helm-match-item ((t (:background unspecified :foreground unspecified :underline t))))
   `(helm-minibuffer-prompt ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-moccur-buffer ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-mode-prefix ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-non-file-buffer ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-prefarg ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-resume-need-update ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-selection ((t (:background ,vb-foreground :foreground ,vb-background))))
   `(helm-selection-line ((t (:background ,vb-foreground :foreground ,vb-background))))
   `(helm-separator ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-source-header ((t (:background unspecified :foreground ,vb-foreground))))
   `(helm-visible-mark ((t (:background unspecified :foreground ,vb-foreground))))
   `(help-argument-name ((t (:background unspecified :foreground ,vb-foreground))))
   `(highlight ((t (:background ,vb-foreground :foreground ,vb-background))))
   `(hl-line ((t (:background ,vb-foreground :foreground ,vb-background))))
   `(holiday ((t (:background unspecified :foreground ,vb-foreground))))
   `(homoglyph ((t (:background unspecified :foreground ,vb-foreground))))
   `(ibuffer-locked-buffer ((t (:background unspecified :foreground ,vb-foreground))))
   `(ido-first-match ((t (:background unspecified :foreground ,vb-foreground))))
   `(ido-incomplete-regexp ((t (:background unspecified :foreground ,vb-foreground))))
   `(ido-indicator ((t (:background unspecified :foreground ,vb-foreground))))
   `(ido-only-match ((t (:background unspecified :foreground ,vb-foreground))))
   `(ido-subdir ((t (:background unspecified :foreground ,vb-foreground))))
   `(ido-virtual ((t (:background unspecified :foreground ,vb-foreground))))
   `(info-header-node ((t (:background unspecified :foreground ,vb-foreground))))
   `(info-header-xref ((t (:background unspecified :foreground ,vb-foreground))))
   `(info-index-match ((t (:background unspecified :foreground ,vb-foreground))))
   `(info-menu-header ((t (:background unspecified :foreground ,vb-foreground))))
   `(info-menu-star ((t (:background unspecified :foreground ,vb-foreground))))
   `(info-node ((t (:background unspecified :foreground ,vb-foreground))))
   `(info-title-1 ((t (:background unspecified :foreground ,vb-foreground))))
   `(info-title-2 ((t (:background unspecified :foreground ,vb-foreground))))
   `(info-title-3 ((t (:background unspecified :foreground ,vb-foreground))))
   `(info-title-4 ((t (:background unspecified :foreground ,vb-foreground))))
   `(info-xref ((t (:background unspecified :foreground ,vb-foreground))))
   `(info-xref-visited ((t (:background unspecified :foreground ,vb-foreground))))
   `(internal-border ((t (:background unspecified :foreground ,vb-foreground))))
   `(isearch ((t (:background ,vb-foreground :foreground ,vb-background))))
   `(isearch-fail ((t (:background ,vb-red :foreground ,vb-background))))
   `(italic ((t (:background unspecified :foreground unspecified :italic t))))
   `(lazy-highlight ((t (:background ,vb-very-subtle :foreground ,vb-foreground))))
   `(ledger-font-C-amount-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-C-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-D-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-N-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-N-symbol-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-account-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-account-name-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-alias-definition-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-alias-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-apply-account-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-apply-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-apply-tag-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-assert-condition-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-assert-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-auto-xact-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-bucket-account-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-bucket-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-capture-account-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-capture-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-capture-regex-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-check-condition-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-check-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-code-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-comment-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-commodity-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-commodity-format-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-commodity-name-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-condition-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-default-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-define-body-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-define-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-define-name-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-end-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-expr-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-expr-expression-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-fixed-commodity-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-fixed-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-fixed-price-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-format-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-include-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-include-filename-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-note-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-note-text-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-other-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-payee-cleared-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-payee-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-payee-name-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-payee-pending-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-payee-regex-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-payee-uncleared-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-pending-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-periodic-xact-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-posting-account-cleared-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-posting-account-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-posting-account-pending-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-posting-amount-cleared-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-posting-amount-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-posting-amount-pending-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-posting-date-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-price-date-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-price-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-price-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-price-symbol-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-reconciler-cleared-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-reconciler-pending-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-reconciler-uncleared-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-report-clickable-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-tag-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-tag-name-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-timeclock-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-uuid-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-uuid-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-xact-cleared-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-xact-highlight-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-xact-pending-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-year-directive-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-font-year-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-occur-narrowed-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(ledger-occur-xact-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(line-number ((t (:background unspecified :foreground ,vb-foreground))))
   `(line-number-current-line ((t (:background unspecified :foreground ,vb-foreground))))
   `(link ((t (:background unspecified :foreground ,vb-foreground))))
   `(link-visited ((t (:background unspecified :foreground ,vb-foreground))))
   `(linum ((t (:background unspecified :foreground ,vb-foreground))))
   `(match ((t (:background unspecified :foreground ,vb-foreground))))
   `(menu ((t (:background unspecified :foreground ,vb-foreground))))
   `(message-cited-text ((t (:background unspecified :foreground ,vb-foreground))))
   `(message-header-cc ((t (:background unspecified :foreground ,vb-foreground))))
   `(message-header-name ((t (:background unspecified :foreground ,vb-foreground))))
   `(message-header-newsgroups ((t (:background unspecified :foreground ,vb-foreground))))
   `(message-header-other ((t (:background unspecified :foreground ,vb-foreground))))
   `(message-header-subject ((t (:background unspecified :foreground ,vb-foreground))))
   `(message-header-to ((t (:background unspecified :foreground ,vb-foreground))))
   `(message-header-xheader ((t (:background unspecified :foreground ,vb-foreground))))
   `(message-mml ((t (:background unspecified :foreground ,vb-foreground))))
   `(message-separator ((t (:background unspecified :foreground ,vb-subtle))))
   `(minibuffer-prompt ((t (:background unspecified :foreground ,vb-foreground))))
   `(mm-command-output ((t (:background unspecified :foreground ,vb-foreground))))
   `(mm-uu-extract ((t (:background unspecified :foreground ,vb-foreground))))
   `(mode-line ((t (:background ,vb-very-subtle :box t :foreground ,vb-foreground))))
   `(mode-line-buffer-id ((t (:background unspecified :bold t :foreground ,vb-foreground))))
   `(mode-line-emphasis ((t (:background unspecified :foreground ,vb-foreground))))
   `(mode-line-highlight ((t (:background unspecified :foreground ,vb-foreground))))
   `(mode-line-inactive ((t (:background ,vb-subtle :box t :foreground ,vb-foreground))))
   `(mouse ((t (:background unspecified :foreground ,vb-foreground))))
   `(mouse-drag-and-drop-region ((t (:background unspecified :foreground ,vb-foreground))))
   `(mu4e-flagged-face ((t (:background unspecified :bold t :foreground ,vb-green))))
   `(nemacs-org-ledger-title ((t (:background unspecified :foreground ,vb-foreground))))
   `(next-error ((t (:background unspecified :foreground ,vb-foreground))))
   `(nobreak-hyphen ((t (:background unspecified :foreground ,vb-foreground))))
   `(nobreak-space ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-calendar-event ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-calendar-sexp ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-clocking ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-column-dateline ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-current-time ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-date ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-date-today ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-date-weekend ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-diary ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-dimmed-todo-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-done ((t (:background unspecified :foreground ,vb-foreground :strike-through t))))
   `(org-agenda-filter-category ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-filter-effort ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-filter-regexp ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-filter-tags ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-restriction-lock ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-agenda-structure ((t (:background unspecified :foreground ,vb-foreground :height 160))))
   `(org-archived ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-block ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-block-begin-line ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-block-end-line ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-bullets ((t (:background unspecified :foreground ,vb-foreground :height 110))))
   `(org-checkbox ((t (:background ,vb-very-subtle :foreground ,vb-foreground))))
   `(org-checkbox-statistics-done ((t (:background unspecified :foreground ,vb-green))))
   `(org-checkbox-statistics-todo ((t (:background unspecified :bold t :foreground ,vb-red))))
   `(org-clock-overlay ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-code ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-column ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-column-title ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-date ((t (:background unspecified :foreground ,vb-subtle))))
   `(org-date-selected ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-default ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-document-info ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-document-info-keyword ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-document-title ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-done ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-drawer ((t (:background unspecified :foreground ,vb-subtle))))
   `(org-ellipsis ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-footnote ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-formula ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-headline-done ((t (:background unspecified :foreground ,vb-foreground :strike-through t))))
   `(org-hide ((t (:background ,vb-background :foreground ,vb-background))))
   `(org-indent ((t (:background ,vb-background :foreground ,vb-background))))
   `(org-latex-and-related ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-level-1 ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-level-2 ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-level-3 ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-level-4 ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-level-5 ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-level-6 ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-level-7 ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-level-8 ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-link ((t (:background unspecified :foreground ,vb-foreground :underline t))))
   `(org-list-dt ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-macro ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-meta-line ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-mode-line-clock ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-mode-line-clock-overrun ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-priority ((t (:background unspecified :foreground ,vb-foreground :italic t))))
   `(org-property-value ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-quote ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-scheduled ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-scheduled-previously ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-scheduled-today ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-sexp-date ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-special-keyword ((t (:background unspecified :foreground ,vb-subtle))))
   `(org-super-agenda-header ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-table ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-tag ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-tag-group ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-target ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-time-grid ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-todo ((t (:background unspecified :bold t :foreground ,vb-foreground))))
   `(org-upcoming-deadline ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-verbatim ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-verse ((t (:background unspecified :foreground ,vb-foreground))))
   `(org-warning ((t (:background unspecified :foreground ,vb-foreground))))
   `(outline-1 ((t (:background unspecified :foreground ,vb-foreground))))
   `(outline-2 ((t (:background unspecified :foreground ,vb-foreground))))
   `(outline-3 ((t (:background unspecified :foreground ,vb-foreground))))
   `(outline-4 ((t (:background unspecified :foreground ,vb-foreground))))
   `(outline-5 ((t (:background unspecified :foreground ,vb-foreground))))
   `(outline-6 ((t (:background unspecified :foreground ,vb-foreground))))
   `(outline-7 ((t (:background unspecified :foreground ,vb-foreground))))
   `(outline-8 ((t (:background unspecified :foreground ,vb-foreground))))
   `(package-description ((t (:background unspecified :foreground ,vb-foreground))))
   `(package-help-section-name ((t (:background unspecified :foreground ,vb-foreground))))
   `(package-name ((t (:background unspecified :foreground ,vb-foreground))))
   `(package-status-avail-obso ((t (:background unspecified :foreground ,vb-foreground))))
   `(package-status-available ((t (:background unspecified :foreground ,vb-foreground))))
   `(package-status-built-in ((t (:background unspecified :foreground ,vb-foreground))))
   `(package-status-dependency ((t (:background unspecified :foreground ,vb-foreground))))
   `(package-status-disabled ((t (:background unspecified :foreground ,vb-foreground))))
   `(package-status-external ((t (:background unspecified :foreground ,vb-foreground))))
   `(package-status-held ((t (:background unspecified :foreground ,vb-foreground))))
   `(package-status-incompat ((t (:background unspecified :foreground ,vb-foreground))))
   `(package-status-installed ((t (:background unspecified :foreground ,vb-foreground))))
   `(package-status-new ((t (:background unspecified :foreground ,vb-foreground))))
   `(package-status-unsigned ((t (:background unspecified :foreground ,vb-foreground))))
   `(page-break-lines ((t (:background unspecified :foreground ,vb-foreground))))
   `(query-replace ((t (:background unspecified :foreground ,vb-foreground))))
   `(read-multiple-choice-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(rectangle-preview ((t (:background unspecified :foreground ,vb-foreground))))
   `(region ((t (:background ,vb-foreground :distant-foreground ,vb-background :foreground ,vb-background))))
   `(rmail-header-name ((t (:background unspecified :foreground ,vb-foreground))))
   `(rmail-highlight ((t (:background unspecified :foreground ,vb-foreground))))
   `(scroll-bar ((t (:background unspecified :foreground ,vb-foreground))))
   `(secondary-selection ((t (:background unspecified :foreground ,vb-foreground))))
   `(shadow ((t (:background unspecified :foreground ,vb-foreground))))
   `(show-paren-match ((t (:background unspecified :bold t :foreground ,vb-green))))
   `(show-paren-match-expression ((t (:background unspecified :bold t :foreground ,vb-green))))
   `(show-paren-mismatch ((t (:background unspecified :foreground ,vb-red :underline t))))
   `(shr-link ((t (:background unspecified :foreground ,vb-foreground))))
   `(shr-strike-through ((t (:background unspecified :foreground ,vb-foreground))))
   `(speedbar-button-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(speedbar-directory-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(speedbar-file-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(speedbar-highlight-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(speedbar-selected-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(speedbar-separator-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(speedbar-tag-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(success ((t (:background unspecified :foreground ,vb-foreground))))
   `(term ((t (:background unspecified :foreground ,vb-foreground))))
   `(term-bold ((t (:background unspecified :foreground ,vb-foreground))))
   `(term-color-black ((t (:background unspecified :foreground ,vb-foreground))))
   `(term-color-blue ((t (:background unspecified :foreground ,vb-foreground))))
   `(term-color-cyan ((t (:background unspecified :foreground ,vb-foreground))))
   `(term-color-green ((t (:background unspecified :foreground ,vb-foreground))))
   `(term-color-magenta ((t (:background unspecified :foreground ,vb-foreground))))
   `(term-color-red ((t (:background unspecified :foreground ,vb-foreground))))
   `(term-color-white ((t (:background unspecified :foreground ,vb-foreground))))
   `(term-color-yellow ((t (:background unspecified :foreground ,vb-foreground))))
   `(term-underline ((t (:background unspecified :foreground ,vb-foreground))))
   `(tool-bar ((t (:background unspecified :foreground ,vb-foreground))))
   `(tooltip ((t (:background unspecified :foreground ,vb-foreground))))
   `(trailing-whitespace ((t (:background unspecified :foreground ,vb-foreground))))
   `(tty-menu-disabled-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(tty-menu-enabled-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(tty-menu-selected-face ((t (:background unspecified :foreground ,vb-foreground))))
   `(underline ((t (:background unspecified :foreground ,vb-foreground))))
   `(variable-pitch ((t (:background unspecified :foreground ,vb-foreground))))
   `(vc-conflict-state ((t (:background unspecified :foreground ,vb-foreground))))
   `(vc-edited-state ((t (:background unspecified :foreground ,vb-foreground))))
   `(vc-locally-added-state ((t (:background unspecified :foreground ,vb-foreground))))
   `(vc-locked-state ((t (:background unspecified :foreground ,vb-foreground))))
   `(vc-missing-state ((t (:background unspecified :foreground ,vb-foreground))))
   `(vc-needs-update-state ((t (:background unspecified :foreground ,vb-foreground))))
   `(vc-removed-state ((t (:background unspecified :foreground ,vb-foreground))))
   `(vc-state-base ((t (:background unspecified :foreground ,vb-foreground))))
   `(vc-up-to-date-state ((t (:background unspecified :foreground ,vb-foreground))))
   `(vertical-border ((t (:background unspecified :foreground ,vb-foreground))))
   `(vterm-color-black ((t (:background unspecified :foreground ,vb-foreground))))
   `(vterm-color-blue ((t (:background unspecified :foreground ,vb-foreground))))
   `(vterm-color-cyan ((t (:background unspecified :foreground ,vb-foreground))))
   `(vterm-color-default ((t (:background unspecified :foreground ,vb-foreground))))
   `(vterm-color-green ((t (:background unspecified :foreground ,vb-foreground))))
   `(vterm-color-magenta ((t (:background unspecified :foreground ,vb-foreground))))
   `(vterm-color-red ((t (:background unspecified :foreground ,vb-foreground))))
   `(vterm-color-white ((t (:background unspecified :foreground ,vb-foreground))))
   `(vterm-color-yellow ((t (:background unspecified :foreground ,vb-foreground))))
   `(warning ((t (:background unspecified :foreground ,vb-foreground))))
   `(whitespace-big-indent ((t (:background unspecified :foreground ,vb-foreground))))
   `(whitespace-empty ((t (:background unspecified :foreground ,vb-foreground))))
   `(whitespace-hspace ((t (:background unspecified :foreground ,vb-foreground))))
   `(whitespace-indentation ((t (:background unspecified :foreground ,vb-foreground))))
   `(whitespace-line ((t (:background unspecified :foreground ,vb-foreground))))
   `(whitespace-newline ((t (:background unspecified :foreground ,vb-foreground))))
   `(whitespace-space ((t (:background unspecified :foreground ,vb-foreground))))
   `(whitespace-space-after-tab ((t (:background unspecified :foreground ,vb-foreground))))
   `(whitespace-space-before-tab ((t (:background unspecified :foreground ,vb-foreground))))
   `(whitespace-tab ((t (:background unspecified :foreground ,vb-foreground))))
   `(whitespace-trailing ((t (:background unspecified :foreground ,vb-foreground))))
   `(widget-button ((t (:background unspecified :bold t :foreground ,vb-foreground))))
   `(widget-button-pressed ((t (:background unspecified :foreground ,vb-foreground))))
   `(widget-documentation ((t (:background unspecified :foreground ,vb-foreground))))
   `(widget-field ((t (:background unspecified :foreground ,vb-foreground))))
   `(widget-inactive ((t (:background unspecified :foreground ,vb-foreground))))
   `(widget-single-line-field ((t (:background unspecified :foreground ,vb-foreground))))
   `(window-divider ((t (:background unspecified :foreground ,vb-foreground))))
   `(window-divider-first-pixel ((t (:background unspecified :foreground ,vb-foreground))))
   `(window-divider-last-pixel ((t (:background unspecified :foreground ,vb-foreground))))))
