(deftheme nawe
  "A nice low-contrast theme inspired in Zenburn (which I love),
Jonathan Blow's Emacs theme and this guy's theme
https://github.com/pixlark/JonathanBlowEmacsTheme")

(custom-theme-set-faces
 'nawe
 '(cursor ((t (:background "#bfebbf")))) ;; only when window-system
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Monospace" :foundry "outline" :width normal :height 98 :weight normal :slant normal))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "turquoise3" :weight normal))))
 '(highlight ((t (:background "#404040"))))
 '(region ((t (:background "#202020" :foreground "#ffffef" :weight bold))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:background "yellow")) (((class color) (min-colors 16) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((t (:background "red"))))
 '(font-lock-builtin-face ((t (:foreground "grey94"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#eee926"))))
 '(font-lock-comment-face ((t (:foreground "#eee926"))))
 '(font-lock-constant-face ((t (:foreground "cyan2"))))
 '(font-lock-doc-face ((t (:foreground "#bcc1c5"))))
 '(font-lock-function-name-face ((t (:foreground "burlywood"))))
 '(font-lock-keyword-face ((t (:foreground "grey94"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "grey94"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#bcc1c5"))))
 '(font-lock-type-face ((t (:foreground "SeaGreen1"))))
 '(font-lock-variable-name-face ((t (:foreground "burlywood"))))
 '(font-lock-warning-face ((t (:foreground "#eee926" :background nil :weight bold :underline t))))
 '(show-paren-match-face ((t (:background "SkyBlue2" :foreground "black"))))
 '(js2-external-variable ((t (:foreground "burlywood"))))
 '(button ((t (:inherit (link)))))
 '(link ((((class color) (min-colors 88) (background light)) (:underline (:color foreground-color :style line) :foreground "RoyalBlue3")) (((class color) (background light)) (:underline (:color foreground-color :style line) :foreground "blue")) (((class color) (min-colors 88) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan1")) (((class color) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan")) (t (:inherit (underline)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline (:color foreground-color :style line) :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "black" :background "white")) (((class mono) (background dark)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "white" :background "black"))))
 '(tooltip ((t (:foreground "systeminfotext" :background "systeminfowindow" :inherit (variable-pitch)))))
 '(mode-line ((t (:foreground "#202020" :background "burlywood" :box (:line-width -1 :color nil :style released-button)))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#202020" :background "#3e3e5e"))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#2f2f2f" :background "grey75"))))
 '(isearch ((t (:weight normal :foreground "brown4" :background "IndianRed"))))
 '(isearch-fail ((t (:background "brown" :foreground "grey94" :weight bold))))
 '(lazy-highlight ((t (:background "PaleGreen4" :foreground "grey94"))))
 '(match ((t (:background "yellow1"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:inherit nil :stipple nil :background "gray16" :foreground "burlywood" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :foundry "outline" :family "Monospace")))))

(provide-theme 'nawe)
